### ISSUE TITLE
Sharper Window Addition?

### ISSUE THREAD

**Issue by expliked** [Shermii/Nix#1]
I've noticed that the IDE itself looks a *tad* bit blurry/fuzzy. I've added this bit of code to my copy of the IDE:
```
# This increases the overall sharpness of the window:
import platform, ctypes
if int(platform.release()) >= 8:
	ctypes.windll.shcore.SetProcessDpiAwareness(True)
# It will also increases the sharpness of the File Explorer window and the popup menu for the settings.
```
As a test I took two pictures, one with and one without the added code.

Before:
![Nix_ _phk3 py_ 9_1_2020 3_03_15 PM](https://user-images.githubusercontent.com/61853266/91910780-81fdcc80-ec64-11ea-973e-96845b3f5b50.png)

After:
![Nix_ _phk3 py_ 9_1_2020 3_02_26 PM](https://user-images.githubusercontent.com/61853266/91910787-8629ea00-ec64-11ea-862e-f050fd3cd5ea.png)

Much better!

Although it would be nice to add to the actual version, I can't confirm that this works with Linux/OS X so I don't recommend adding this until proven working for all platforms.

**Comment by Bugyna** [comment]
Hello. Thank you for your advice and recommendation. I will check if it works on other platforms too. I've never really noticed the issue because of my bad eye sight so thanks again.

**Comment by Bugyna** [comment]
I am not very sure if it really works the way it's supposed to but calling: _root.tk.call("tk", "scaling", **1.35**)_ seems to do the trick on both Windows and Linux (it's a bit less noticeable in Linux). It seems that the value(**1.35**) should be different if you have a higher resolution so I'll add a command for changing the value (and eventually add it to the settings menu)
